// What a person reads: the guided menu, the setup wizard, the window of a
// consent, the first message to the agent. In the user's language (the
// research language), English built in, other languages in the same catalogs
// as the research phrases (assets/lang/<code>.json, keys ui.*).

import { localized } from "../core/phrases.ts";

export const UI = {
  "ui.yes": "y",
  "ui.no": "n",
  "ui.enter": "Press Enter to go back to the menu.",
  "ui.choose": "Choose",
  "ui.bad.choice": "Please type one of the numbers.",

  "ui.dialog.title": "Strom research",
  "ui.dialog.yes": "Allow",
  "ui.dialog.no": "Don't allow",
  "ui.dialog.refused": "You did not allow it — nothing was changed.",
  "ui.consent.level.auto": "Let the agent work on its own? It will ask you only about risky steps.",
  "ui.consent.level.full": "Let the agent do everything except what strom forbids, without asking you?\n\nOnly for a computer where nothing else of value is kept.",
  "ui.consent.connector": "Allow the downloader \"{name}\" to fetch images for the research?",
  "ui.consent.connector.revoke": "Stop the downloader \"{name}\"?",
  "ui.consent.host.pace": "Your own pace for {host}: at least {seconds} s between two requests, {cap}. Going too fast slows the archive for everyone and can get your IP blocked — set it so?",
  "ui.pace.cap": "at most {n} an hour",
  "ui.pace.nocap": "no hourly cap",
  "ui.consent.host": "Allow automatic downloading from {host}?",
  "ui.consent.host.revoke": "Stop automatic downloading from {host}?",
  "ui.consent.connector.hosts": "It will reach only {hosts} — slowly, through strom's limiter.",
  "ui.consent.connector.changed": "Its code changed since you allowed it.",
  "ui.consent.connector.direct": "Warning: its code reaches the network itself, past strom's limiter.",
  "ui.consent.connector.terms": "The archive's terms of use: {terms}",
  "ui.consent.host.unblock": "{host} refused us. Allow it again — only if the archive said it is fine?",
  "ui.consent.connectors.off": "Let downloaders run without asking you first?",

  "ui.migrated": "The family tree's data were brought up to date for this version of strom ({step}).",
  "ui.menu.title": "Strom research {version}",
  "ui.menu.tree": "Family tree: {name} · {persons} people",
  "ui.menu.waiting": "Waiting for you: {count}",
  "ui.menu.working": "The agent is working on its own right now.",
  "ui.menu.chat": "Continue the research with the agent",
  "ui.menu.start": "Start the research with the agent",
  "ui.menu.otheragent": "Talk with another agent this time",
  "ui.menu.run": "Let the agent work on its own",
  "ui.menu.waitlist": "What waits for you",
  "ui.menu.settings": "Settings: the agent, working alone, messages, archives, the check",
  "ui.menu.doctor": "Check the installation",
  "ui.menu.trees": "Another family tree",
  "ui.menu.newtree": "Create a family tree",
  "ui.menu.quit": "Quit",
  "ui.menu.bye": "See you next time. Start again with: strom",

  "ui.run.how": "How many tasks? (it stops earlier when there is nothing to do; 0 goes back)",
  "ui.run.start": "The agent works on its own now. You can stop it with Ctrl-C — nothing is lost.",
  "ui.waiting.none": "Nothing waits for you.",
  "ui.waiting.open": "Open the folder for the images?",
  "ui.results.files": "Results (updated after every session):",
  "ui.results.none": "No results yet — they appear after the first session.",
  "ui.results.app": "For the Strom app: {file} — in the app choose Import and pick this file.",
  "ui.results.app.maybe": "Do you use the Strom app? Import {file} into it.",
  "ui.results.open": "Open the folder with the results?",
  "ui.trees.pick": "Which family tree?",
  "ui.trees.new": "a new family tree",
  "ui.tree.name": "What should your family tree be called? (e.g. the family surname)",
  "ui.tree.default": "My family",
  "ui.chat.open": "Opening the conversation with the agent ({agent}). When you are done, type {exit}.",
  "ui.chat.first": "Hello, I want to start researching my ancestors. Run `strom`, explain to me in a few sentences how we will work together, and ask me whom we are looking for and what we already know.",
  "ui.chat.continue": "Let's continue the research. Run `strom`, tell me briefly where the research stands and what waits for me, and suggest what to do next.",

  "ui.setup.welcome": "Welcome to Strom research. Let's set up a few things — press Enter to accept the suggested answer.",
  "ui.setup.again": "Settings — press Enter to keep the current value.",
  "ui.setup.lang": "Language (cs, en, de, pl, …)",
  "ui.setup.home": "Where to keep the research",
  "ui.setup.git.ok": "✓ Git (history of the research): {version}",
  "ui.setup.git.missing": "Git is missing — strom keeps the history of the research in it, so nothing gets lost.",
  "ui.setup.git.wait": "Finish the installation in the window that opened, then press Enter.",
  "ui.setup.git.manual": "Install it with: {command} — then start strom again.",
  "ui.setup.agent.ok": "✓ AI agent: {name}",
  "ui.setup.agent.pick": "Which AI agent should do the research?",
  "ui.setup.agent.none": "No AI agent found — strom needs one: the agent does the research with you.",
  "ui.setup.agent.install": "Install Claude Code now (recommended; you need a Claude subscription)",
  "ui.setup.agent.guide": "Show me which agents there are (opens a page in the browser)",
  "ui.setup.agent.later": "Later",
  "ui.setup.agent.login": "The first time the agent starts, you log in — a browser window opens.",
  "ui.setup.agent.manual": "Install an AI agent (how: {url}), then start strom again.",
  "ui.setup.model": "Which model should do the research?",
  "ui.setup.model.opus": "Opus — best at reading old handwriting (recommended)",
  "ui.setup.model.sonnet": "Sonnet — faster; printed documents and everyday work",
  "ui.setup.model.own": "Leave it to the agent",
  "ui.setup.level": "What may the agent do without asking you?",
  "ui.setup.level.ask": "Ask me about everything outside the research",
  "ui.setup.level.auto": "Work on its own — ask only about risky steps (recommended)",
  "ui.setup.level.full": "Everything without asking — only on a computer with nothing else of value",
  "ui.setup.level.warn": "The agent will be able to run any program and change any of your files; strom still guards the research itself.",
  "ui.setup.level.sure": "Really allow everything?",
  "ui.setup.shortcut": "Put a \"Strom research\" shortcut on the desktop?",
  "ui.setup.shortcut.done": "✓ Shortcut: {file}",
  "ui.setup.skill": "✓ {agent} now knows strom in any folder.",
  "ui.setup.app": "✓ The Strom app is on this computer — the menu opens the research in it, and while the agent works the app follows it live.",
  "ui.setup.done": "All set.",
  "ui.setup.stromapp": "The Strom app (free, in the browser) shows the research as a family tree — each entry with its image cut out of the scan, the stories of the ancestors — and follows it live while the agent works. Do you want to use it?",
  "ui.setup.stromapp.install": "Yes — install it now (it opens in the browser, strom says where to click)",
  "ui.setup.stromapp.later": "Yes, but not now",
  "ui.setup.stromapp.no": "No — do not mention it again",
  "ui.menu.app.watch": "Watch the agent at work in the Strom app (live)",
  "ui.menu.app.new": "The Strom app — the research as a family tree, followed live",
  "ui.menu.app.tip": "Tip: the research can be seen as a family tree in the Strom app, and followed live while the agent works — choice {key}.",
  "ui.menu.app.live": "The agent is at work — you can watch it live in the Strom app: choice {key}.",
  "ui.app.open.now": "Once it is installed: open the research in it?",
  "ui.run.follow": "Watch the work live in the Strom app meanwhile?",
  "ui.app.opened": "Opening the Strom app ({where}).",
  "ui.app.browser": "in your browser",
  "ui.app.url": "Open it here: {url}",
  "ui.app.installed": "The Strom app is installed ({kind}).",
  "ui.app.install": "The Strom app opened in your browser. To install it as an app, click the install icon at the right end of the address bar (Chrome, Edge); in Safari choose File → Add to Dock.",
  "ui.menu.app": "Open the research in the Strom app",
  "ui.chat.agent.missing": "{agent} is not installed — run the settings (strom setup) to install it.",
  "ui.shortcut.done": "Shortcut on the desktop: {file}",
  "ui.o.title": "strom {version} — genealogical research toolkit for AI agents",
  "ui.o.rule": "The evidence lives here; change it ONLY through strom commands. New here: strom guide",
  "ui.o.home": "home",
  "ui.o.notsetup": "(not set up)",
  "ui.o.tree": "tree",
  "ui.o.lang": "lang",
  "ui.o.langnote": "talk to the user and write research texts in this language",
  "ui.o.data": "data",
  "ui.o.counts": "{persons} persons · {families} families · check: {check}",
  "ui.o.ok": "ok",
  "ui.o.errors": "{n} errors",
  "ui.o.warnings": "{n} warnings",
  "ui.o.research": "research",
  "ui.o.research.none": "research (none yet)",
  "ui.o.trees": "trees",
  "ui.o.working": "working now (other agents — never take their tasks)",
  "ui.o.since": "since {time}",
  "ui.o.on": "on {task}",
  "ui.o.next": "next",
  "ui.why.setup.human": "strom is not set up yet — it asks where to keep the research",
  "ui.why.setup.agent": "strom is not set up yet: this creates {home} (tell the user; --home <dir> for another place)",
  "ui.why.init": "there is no family tree yet",
  "ui.why.pick": "several trees exist — pick one (it is remembered)",
  "ui.why.check": "the evidence has problems (or was changed outside strom)",
  "ui.why.runleft": "session {id} was left open by a run that stopped — the next run closes it and goes on",
  "ui.why.running": "strom run is working (session {id}) — let it finish, or Ctrl-C in its window",
  "ui.why.open.human": "session {id} is open — an agent is working, or it stopped without closing",
  "ui.why.open.agent": "session {id} is open{on} — continue, then close it",
  "ui.why.research": "the tree has no research yet",
  "ui.why.waiting": "the research waits for you — see \"waiting for you\" above",
  "ui.why.intake": "record first what the user knows (then tasks follow from it)",
  "ui.why.run": "{n} task(s) in the queue — an AI agent works them",
  "ui.why.session": "{n} task(s) in the queue",
  "ui.why.frontier": "no open tasks — see what the research still lacks",
  "ui.wait.title": "waiting for you ({n})",
  "ui.wait.images": "images {images} of {book}",
  "ui.wait.save": "save them into {dir}",
  "ui.wait.how1": "scans go into the inbox, a folder per book, each named by its image number as the viewer counts it",
  "ui.wait.how2": "(9.jpg; a zoomed-in part of it: 9a.jpg) — the next run registers them and the task comes back by itself",
  "ui.run.summary": "{n} session(s) · stopped: {reason}",
  "ui.run.stop.done": "done",
  "ui.run.stop.user": "stopped by you",
  "ui.run.stop.time": "time limit",
  "ui.run.stop.empty": "no open tasks",
  "ui.run.stop.problems": "the evidence has problems — strom check",
  "ui.run.stop.denied": "the agent was not allowed to run strom — its permissions are wrong (.claude/settings.json of the tree); nothing more was started",
  "ui.run.stop.limit": "subscription limit{resets}",
  "ui.run.stop.resets": " (resets {at})",
  "ui.run.stop.auth": "the agent is not logged in — run {command} once and log in",
  "ui.run.stop.failed": "the agent failed: {detail}",
  "ui.run.stopping": "■ stopping — the session is closed and its task goes back to the queue; Ctrl-C again to quit at once",
  "ui.run.gone": "· {session} closed — its run had stopped{back}",
  "ui.run.back": "; {task} is back in the queue",
  "ui.run.start.session": "▶ {session} · {task} {what}",
  "ui.run.parked": "  · {task} parked: {n} sessions in a row recorded nothing",
  "ui.run.denied": "  · permissions refused {n}×: {what}",
  "ui.tree.created": "✓ The family tree \"{name}\" is ready: {dir}",
  "ui.chat.trust": "The first time, Claude Code asks whether you trust this folder. It is your family tree's folder, made by strom — confirm with \"Yes, proceed\".",
  "ui.doc.program": "program",
  "ui.doc.git": "git (history)",
  "ui.doc.home": "research folder",
  "ui.doc.shared": "scans and catalog",
  "ui.doc.trees": "family trees",
  "ui.doc.agent": "AI agents",
  "ui.doc.knows": "agents know strom",
  "ui.doc.level": "the agent may",
  "ui.doc.model": "model",
  "ui.doc.shortcut": "desktop shortcut",
  "ui.doc.app": "Strom app",
  "ui.doc.tree": "this family tree",
  "ui.doc.innode": "strom {version} in Node {node}",
  "ui.doc.oldnode": "Node {node} is too old (22.18 or newer)",
  "ui.doc.missing": "missing",
  "ui.doc.notsetup": "not set up yet",
  "ui.doc.none": "none",
  "ui.doc.yes": "yes",
  "ui.doc.default": "default",
  "ui.doc.noagent": "no AI agent installed",
  "ui.doc.knows.yes": "yes, in any folder",
  "ui.doc.knows.no": "not yet: {agents}",
  "ui.doc.app.yes": "you use it",
  "ui.doc.app.seen": "found on this computer",
  "ui.doc.app.no": "not wanted",
  "ui.doc.app.unknown": "not found",
  "ui.doc.tree.ok": "{name}: data consistent and sealed",
  "ui.doc.tree.bad": "{name}: {n} problem(s)",
  "ui.doc.allok": "Everything needed is in place.",
  "ui.doc.problems": "{n} problem(s) — do what the arrows say (strom setup offers to install what is missing).",
  "ui.menu.fix": "Fix it now?",
  "ui.chat.app.open": "The conversation opens in the {app} app. Confirm the family tree's folder there, then send the prepared message (Enter).",
  "ui.chat.app.closed": "The {app} app did not open. Start it yourself, open the folder {dir} and write: {message}",
  "ui.chat.app.auto": "So that the agent works on its own: in the menu under the message box choose \"Auto\" — once, Claude remembers it for this folder.",
  "ui.chat.app.full": "So that the agent may do everything: in the menu under the message box choose \"Bypass permissions\" (turn it on in Claude's settings first).",
  "ui.setup.where": "Where do you want to talk with the agent?",
  "ui.setup.where.app": "In the {app} app — the easiest (recommended)",
  "ui.setup.where.terminal": "In the terminal ({agent}) — for experienced users",
  "ui.doc.where": "where you talk",
  "ui.doc.where.app": "the {app} app",
  "ui.doc.where.terminal": "the terminal ({agent})",
  "ui.run.needscli": "Working on its own needs {agent} in the terminal (the app alone cannot) — strom setup offers to install it.",
  "ui.fix.git.download": "Download git for strom (about {mb} MB — the official Git for Windows, used by strom only, no installation)?",
  "ui.fix.git.window": "Git comes with Apple's command line tools. A window of the system installs them (a few minutes). Open it?",
  "ui.fix.git.downloading": "Downloading git…",
  "ui.fix.git.inwindow": "Finish the installation in the window of the system, then run strom doctor again.",
  "ui.fix.failed": "It did not work: {detail}",
  "ui.fix.app": "Open the Strom app in the browser, to install it?",
  "ui.fix.nothing": "Nothing strom can fix by itself — see the arrows.",
  "ui.why.git.human": "git is missing — strom keeps the history of the research in it",
  "ui.why.git.agent": "git is missing (strom keeps the research history in it): tell the user, then run this — the user says yes in a window of the system",
  "ui.o.results": "results",
  "ui.o.results.installed": "{file} — for the Strom app, installed here: strom app opens it (in the app: Import; on the web: {url})",
  "ui.o.results.offer": "{file} — for the Strom app, not installed here yet: offer the user to install it from {url} (strom app install opens it there)",
  "ui.o.results.offered": "{file} — for the Strom app, not installed here; the user has heard of it — bring it up again only when they want to see the results (strom app install, then strom app)",
  "ui.o.ask": "asking",
  "ui.o.ask.tell": "tell the user once, in a sentence, that they can ask you here about anyone in the tree — strom says this once",
  "ui.o.results.plain": "{file} — for any family tree program",
  "ui.o.results.installed.live": "{file} — for the Strom app, installed here: strom app opens this research in it, and while you work the app follows it live (what you record shows there by itself) — offer it (strom says this once)",
  "ui.o.results.offer.live": "{file} — for the Strom app, not installed here yet: offer the user to watch the research grow in it live — installed from {url} (strom app install opens it there and says where to click), then strom app",
  "ui.chat.handover": "The research goes on in its own conversation: a new window opened with {agent} in your family tree's folder. Continue there — this conversation can end.",
  "ui.chat.handover.failed": "A new window could not be opened here. Start the research yourself: run strom in a terminal (or the Strom research shortcut on the desktop).",
  "ui.chat.handover.recent": "A window with the research and {agent} opened a moment ago — continue there. This conversation can end.",
  "ui.chat.handover.end": "Continue there — this conversation can end.",
  "ui.why.handover": "the research belongs in its own conversation in the tree folder (its permissions, no asking at every step): this opens it — tell the user to continue there; go on here only if they want",
  "ui.app.research": "Opening the research {name} in the Strom app ({where}): the first time as a new tree, after that the same tree, updated.",
  "ui.app.following": "The Strom app follows the research {name} while it goes on ({where}): what is found shows there by itself.",
  "ui.menu.review": "Review one person: check and complete what is known of them",
  "ui.review.who": "Whom? (a name or an ID such as P0012; Enter or 0 goes back)",
  "ui.review.none": "Nobody called \"{who}\" in this family tree.",
  "ui.review.pick": "Which one?",
  "ui.review.family": "With their spouse and children?",
  "ui.review.run": "Let the agent work on it now, on its own? ({n} tasks)",
  "ui.o.reread": "second reading",
  "ui.o.reread.offer": "{n} facts rest only on readings by another model ({models}); the user reads with {model} now — offer it once, in a sentence: strom review <whom> --reread (a task per person; the user decides)",
  "ui.o.stories": "stories",
  "ui.o.stories.tell": "on (the default): tell the user (strom says this once) in a sentence that you will also write stories of their ancestors for the family book in the Strom app, and that they may say no — strom config set stories no (yes: strom config set stories yes)",
  "ui.o.stories.on": "on: strom proposes a story once records tell a life (narrate tasks)",
  "ui.o.stories.off": "off (the user said no) — do not bring it up",
  "ui.setup.model.strong": "The research needs a strong model — it reads old handwriting and weighs the records: in {agent}, choose its best model, not a fast or mini one.",
  "ui.chat.app.model": "In {app}, choose its best model for the research (not a fast or mini one): it reads old handwriting.",
  "ui.setup.stories": "Should the agent also write stories of your ancestors — a few paragraphs about each life, from the records it finds, for the family book in the Strom app?",
  "ui.setup.stories.yes": "Yes (recommended)",
  "ui.setup.stories.no": "No — just the family tree and its sources",
  "ui.uninstall.agent": "what {agent} knows of strom",
  "ui.uninstall.shortcut": "the shortcut",
  "ui.uninstall.git": "strom's own git",
  "ui.uninstall.path": "the installer's PATH entry",
  "ui.uninstall.program": "the program",
  "ui.uninstall.list": "strom takes this off your computer:",
  "ui.uninstall.keeps": "Your research stays ({home}), and so do your settings with the keys that seal it ({config}) — delete them yourself only if you never want them again.",
  "ui.uninstall.sure": "Uninstall strom?",
  "ui.uninstall.kept": "Nothing was removed.",
  "ui.uninstall.window": "Uninstall strom from this computer? Your research stays.",
  "ui.uninstall.nothing": "Nothing of strom's to take off this computer.",
  "ui.uninstall.npm": "The program itself (installed with npm): npm uninstall -g strom-research",
  "ui.uninstall.done": "strom is uninstalled. Thank you for researching with it.",
  "ui.menu.update.line": "A new version of strom is out: {version}.",
  "ui.menu.update": "Update strom to {version}",
  "ui.doc.update": "new version",
  "ui.doc.update.new": "{version} is out",
  "ui.update.unknown": "The newest version of strom could not be learned.",
  "ui.update.current": "strom {version} is the newest version.",
  "ui.update.available": "A new version is out: {version} (this is {current}) — strom update installs it.",
  "ui.update.npm": "A new version is out: {version}. strom is installed with npm here: npm install -g strom-research@latest",
  "ui.update.sure": "Update strom from {current} to {version}? Your research stays as it is.",
  "ui.update.later": "Not now — strom update any time.",
  "ui.update.downloading": "Downloading strom {version}…",
  "ui.update.failed": "The update did not work: {detail}. strom stays as it was.",
  "ui.update.done": "✓ strom is updated: {previous} → {version}.",
  "ui.o.update": "update",
  "ui.o.update.new": "{version} is out (this is {current}) — tell the user; strom update installs it with their yes",
  "ui.app.where.installed": "the installed app",
  "ui.app.drag": "The Strom app opened. Drag the file {file}{shown} into its window — the first time it becomes a new tree, after that the same tree is updated. With Chrome or Edge on this computer, strom hands it over by itself.",
  "ui.app.drag.shown": " (shown in the file window)",
  "ui.app.nolive": "Following the research live needs Chrome or Edge — Safari does not let a web page reach this computer.",
  "ui.app.images": "With images: {n} entries cut out of their scans ({mb} MB).",
  "ui.app.images.unclipped": "{n} more sources are on images, but nobody has marked where their entry is yet — the agent can do it.",
  "ui.app.images.smaller": "To fit the limit of {limit} MB, the images are smaller than set: {level} instead of {asked}.",
  "ui.app.images.left": "{n} entries farthest from the research are without their image, to fit the limit of {limit} MB.",
  "ui.app.images.scope": "{n} entries of people farther from the research have no image (setting excerpts.for: {for}).",
  "ui.doc.installed": "strom {version} on its own Node {node} (official, from nodejs.org)",
  "ui.update.source": "A new version is out: {version}. This strom runs from its sources: git pull",
  "ui.update.node.available": "Node {from} → {to}: security fixes of its line — strom update installs them.",
  "ui.update.node.sure": "Update strom's Node from {from} to {to} (security fixes)?",
  "ui.update.node.done": "✓ Node is updated: {from} → {to}.",
  "ui.menu.browse": "Look through the family tree: overview, people, ancestors, what is new",
  "ui.browse.stats": "Overview of the research",
  "ui.browse.recent": "What is new (the last 7 days)",
  "ui.browse.card": "One person: their life, family and records",
  "ui.browse.pedigree": "The ancestors of one person",
  "ui.browse.files": "The result files (GEDCOM)",
  "ui.browse.back": "Back",
  "ui.browse.whose": "Whose ancestors? (a name or an ID such as P0012; 0 goes back)",
  "ui.date.about": "about {date}",
  "ui.date.before": "before {date}",
  "ui.date.after": "after {date}",
  "ui.date.between": "between {a} and {b}",
  "ui.date.fromto": "from {a} to {b}",
  "ui.date.from": "from {date}",
  "ui.date.to": "until {date}",
  "ui.st.proven": "proven",
  "ui.st.probable": "probable",
  "ui.st.possible": "possible",
  "ui.st.lead": "only a lead",
  "ui.ev.BIRT": "birth",
  "ui.ev.CHR": "baptism",
  "ui.ev.DEAT": "death",
  "ui.ev.BURI": "burial",
  "ui.ev.CREM": "cremation",
  "ui.ev.MARR": "marriage",
  "ui.ev.MARB": "banns",
  "ui.ev.ENGA": "engagement",
  "ui.ev.DIV": "divorce",
  "ui.ev.OCCU": "occupation",
  "ui.ev.RESI": "residence",
  "ui.ev.EDUC": "education",
  "ui.ev.RELI": "religion",
  "ui.ev.TITL": "title",
  "ui.ev.CENS": "census",
  "ui.ev.CONF": "confirmation",
  "ui.ev.EMIG": "emigration",
  "ui.ev.IMMI": "immigration",
  "ui.ev.NATU": "naturalisation",
  "ui.ev.PROB": "probate",
  "ui.ev.WILL": "will",
  "ui.gen.2": "parents",
  "ui.gen.3": "grandparents",
  "ui.gen.4": "great-grandparents",
  "ui.gen.5": "great-great-grandparents",
  "ui.gen.n": "generation {n}",
  "ui.card.house": "{place}, house {house}",
  "ui.card.also": "other forms of the name: {names}",
  "ui.card.nofacts": "no facts recorded yet",
  "ui.card.parents": "Parents: {names}",
  "ui.card.noparents": "Parents: not known yet",
  "ui.card.wife": "Wife: {name}",
  "ui.card.husband": "Husband: {name}",
  "ui.card.partner": "Partner: {name}",
  "ui.card.unknown": "not known yet",
  "ui.card.children": "Children: {names}",
  "ui.card.story": "Story:",
  "ui.stats.title": "{name} – the research at a glance",
  "ui.stats.counts": "People: {persons} · families: {families} · records from sources: {sources} · scans: {images} · places: {places}",
  "ui.stats.facts": "Facts: proven {proven} · probable {probable} · possible {possible} · only leads {lead}",
  "ui.stats.from": "Ancestors of {name}:",
  "ui.stats.gen": "{known} of {expected} known · birth proven: {proven}",
  "ui.stats.oldest": "Earliest-born proven ancestor: {name}",
  "ui.stats.noancestors": "No ancestors recorded yet.",
  "ui.stats.tasks": "Tasks: in the queue {queued} · waiting for you {waiting} · done {done}",
  "ui.stats.sessions": "Sessions of the agent: {n} · the last {last}",
  "ui.stats.cost": " · cost so far {cost}",
  "ui.stats.cost.partial": " (without sessions stopped before they said what they cost: {n})",
  "ui.stats.stories": "Stories: {n}",
  "ui.ped.noparents": "parents not known yet",
  "ui.ped.nofather": "father not known yet",
  "ui.ped.nomother": "mother not known yet",
  "ui.ped.seen": "(shown above)",
  "ui.ped.legend": "Father first, then mother · ✓ birth proven by a record",
  "ui.ped.more": "The known ancestors go on to generation {n}: strom pedigree {id} --generations {n}",
  "ui.recent.title": "What came in since {since}",
  "ui.recent.nothing": "Nothing new since {since}.",
  "ui.recent.counts": "New people: {persons} · facts: new {facts}, refined {refined} · records from sources: {sources} · stories: {stories} · tasks done: {done}",
  "ui.recent.persons": "New people:",
  "ui.recent.facts": "New and refined facts:",
  "ui.recent.refined": "refined",
  "ui.recent.stories": "Stories written:",
  "ui.recent.sessions": "What the agent did:",
  "ui.recent.more": "… and {n} more",
  "ui.browse.plan": "What the agent will do next",
  "ui.review.new": "{name} — {n} new task(s):",
  "ui.review.nothing": "{name} — nothing new to review",
  "ui.review.would": "  would add: {level} · {what}",
  "ui.review.dry": "(dry run — nothing written)",
  "ui.review.covered": "  {name}: already covered by {task} ({state}) — {what}",
  "ui.review.wake": "    to go on with it: strom task wake {task}",
  "ui.review.exhausted": "  {name}: searched in vain ({tasks}) — what next is your decision",
  "ui.review.open": "{n} task(s) open in {research}, about as many sessions",
  "ui.review.cost": " — a session here costs ${cost} on average",
  "ui.review.next": "next: strom run --research {research} (the agent alone) · or in a conversation: strom session start --research {research}",
  "ui.review.state.open": "in the queue",
  "ui.review.state.doing": "being worked on",
  "ui.review.state.parked": "parked",
  "ui.review.state.waiting": "waiting for you",
  "ui.plan.title": "What the agent will do next – {name}:",
  "ui.plan.now": "now",
  "ui.plan.images": " (needs the scans first)",
  "ui.plan.more": "… and {n} more tasks",
  "ui.plan.stories": "Then the stories: {n} ({names})",
  "ui.plan.waiting": "Waiting for you: {n} (in the menu: What waits for you)",
  "ui.plan.none": "Nothing in the queue — the agent proposes new tasks after its next session, or tell it in a conversation what to look for.",
  "ui.plan.steer": "To change the order, tell the agent in a conversation what comes first.",
  "ui.plan.session": "the session of {day}",
  "ui.back.stay": "Back – stay with {name}",
  "ui.keep": "Keep it as it is",
  "ui.tree.name.new": "What should the new family tree be called? (e.g. the family surname; 0 goes back)",
  "ui.run.skip": "  · {task} left out: it is done or dropped already",
  "ui.run.skip.held": "  · {task} left out: another agent is working on it",
  "ui.run.next": "Next in the queue, in the order the agent takes them:",
  "ui.run.story": " (a story)",
  "ui.run.what": "What should the agent do?",
  "ui.run.queue": "Work through the queue in this order – you say how many",
  "ui.run.pick": "Only the tasks you pick from the list",
  "ui.run.which": "Which ones? Their numbers, e.g. 2 or 1,4 or 2-5 (0 goes back)",
  "ui.run.which.bad": "Numbers from the list, 1 to {n}: e.g. 2 or 1,4 or 2-5.",
  "ui.run.limit": "One task has at most {minutes} minutes; then the agent is stopped and the task goes back to the queue (setting run.minutes).",
  "ui.run.empty": "Nothing in the queue — tell the agent in a conversation what to look for.",
  "ui.run.browser": "· {name}: images through your browser — the agent gets browser tools for {hosts}; Chrome with the Claude extension must be running",
  "ui.run.browser.model": "  note: browser tools need a model that can review its actions — Sonnet or Opus, not {model}: strom config set model.lead sonnet",
  "ui.run.full": "· permissions: full — the agent does everything but what the tree's permissions deny (back: strom config set agent.permissions auto)",
  "ui.menu.working.more": "{n} agents are working on their own right now.",
  "ui.run.beside": "⚠ An agent is already working on its own here (runs: {n}). Another one beside it takes other tasks — the costs add up.",
  "ui.run.beside.sure": "Start another one beside it?",
  "ui.run.others": "⚠ Another run works in this family tree already (since {since}): this one takes other tasks — the costs add up.",
  "ui.run.gate": "· condition: {name} — asked before each session; it may make the run wait",
  "ui.run.gate.wait": "⏸ waiting until {at} — {reason} (Ctrl-C ends the run)",
  "ui.run.stop.gate": "the condition “{name}” said stop — {reason}",
  "ui.run.stop.gate.error": "the condition “{name}” gave no proper answer — {reason} (strom gate test)",
  "ui.run.gate.once": "· condition: {name} — these tasks are yours to start: it is asked once, and if it would not start, you decide",
  "ui.run.gate.anyway": "The condition “{name}” would not start now — {reason}. Start anyway?",
  "ui.run.gate.later": "not yet",
  "ui.run.gate.no": "no",
  "ui.run.gate.noanswer": "no proper answer (strom gate test)",
  "ui.run.stop.gate.declined": "not started — the condition “{name}”: {reason}",
  "ui.run.loop": "Let it work on while there is work and the condition “{name}” allows it",
  "ui.consent.gate.set": "Let the condition “{name}” decide when the agent working alone goes on?",
  "ui.consent.gate.unset": "Remove the condition “{name}” — the agent working alone no longer asks it?",
  "ui.consent.gate.skip": "Let the agent work on its own without the condition “{name}”?",
  "ui.consent.remote": "Start the Claude Code sessions strom opens with Remote Control, so that you can follow and steer them from claude.ai or the Claude app on your phone?",
  "ui.consent.hook.on": "Let the hook “{name}” be told of everything saved into your researches? It is a program on this computer and does with it what it was written to do.",
  "ui.consent.hook.off": "Stop telling the hook “{name}” what is saved?",
  "ui.menu.more": "Add to the research: material, a new direction, one person reviewed",
  "ui.more.title": "Add to the research",
  "ui.more.intake": "Material from the family: documents, photos, a family tree from another program, what you know",
  "ui.more.research": "A new direction: the ancestors or descendants of someone else, or one question",
  "ui.intake.what": "What do you bring?",
  "ui.intake.files": "Files or a folder from this computer",
  "ui.intake.text": "What you know — names, dates, places, family memories",
  "ui.intake.write": "Write what you know (Enter or 0 goes back)",
  "ui.intake.path": "The folder or file — you can drag it into this window (Enter or 0 goes back)",
  "ui.intake.missing": "Not found: {path} — check the path, or drag the folder in.",
  "ui.intake.scans": "The folder {folder} holds {n} images. Are they family documents and photos? (no: scans of a register or another book)",
  "ui.intake.book": "{folder}: scans of a register or another book go with that book — tell the agent in a conversation where they come from, and it registers them.",
  "ui.intake.known": "This material is in the research already — nothing added.",
  "ui.intake.done": "✓ Added to the research: {n}. The agent goes through it in its next work.",
  "ui.intake.chat": "Go through it with the agent now?",
  "ui.intake.say": "I added new material to the research — let us go through it.",
  "ui.research.kind": "What do you want to find out?",
  "ui.research.ancestors": "The ancestors of someone",
  "ui.research.descendants": "The descendants of someone",
  "ui.research.question": "One question (e.g. who was Mary's father?)",
  "ui.research.ask": "The question (Enter or 0 goes back)",
  "ui.research.whom": "Who is it about?",
  "ui.research.known": "Someone already in the family tree",
  "ui.research.newperson": "Someone new",
  "ui.research.name": "Their name (e.g. John Smith; 0 goes back)",
  "ui.research.sex": "A man or a woman?",
  "ui.research.male": "A man",
  "ui.research.female": "A woman",
  "ui.research.unknown": "I don't know",
  "ui.research.title": "The research's name",
  "ui.research.title.ancestors": "Ancestors: {name}",
  "ui.research.title.descendants": "Descendants: {name}",
  "ui.research.knows": "What do you know of it? Dates, places, stories of the family help the agent (Enter: nothing)",
  "ui.research.done": "✓ The research “{name}” is started.",
  "ui.research.chat": "Start on it with the agent now?",
  "ui.research.say": "I started a new research, “{name}” — let us begin with it.",
  "ui.settings.title": "Settings (on this computer)",
  "ui.settings.wizard": "Language, agent, model, what the agent may do alone, stories… (the setup)",
  "ui.settings.alone": "The agent working alone: {minutes} min a task · condition: {gate}",
  "ui.settings.gate.none": "none",
  "ui.settings.hooks": "Messages of what is saved (hooks): {state}",
  "ui.settings.on": "on",
  "ui.settings.off": "off",
  "ui.settings.remote": "Watch the agent from your phone (Remote Control): {state}",
  "ui.settings.remote.about": "With it on you can follow and steer the Claude Code sessions strom starts — conversations and working alone — from claude.ai or the Claude app on your phone.",
  "ui.settings.remote.on": "Turn it on?",
  "ui.settings.remote.off": "Turn it off?",
  "ui.settings.archives": "Archives: your logins, downloaders asking first",
  "ui.alone.title": "The agent working alone",
  "ui.alone.minutes": "Time for one task: {minutes} min",
  "ui.alone.minutes.ask": "How many minutes may one task take? (5–600; 0 goes back)",
  "ui.alone.minutes.bad": "Please a number of minutes from 5 to 600.",
  "ui.alone.gate": "Working on and on under a condition: {gate}",
  "ui.alone.gate.about": "A condition is asked before each session while the agent works on and on by itself; the menu offers that only with one set. Tasks you start yourself are your choice.",
  "ui.alone.gate.pick": "Which condition?",
  "ui.alone.gate.claude": "By how many points should the week's usage of your Claude subscription stay behind the part of the week gone? (a day ≈ 14.3; 0: just not ahead of the week)",
  "ui.alone.gate.args": "What to give it (Enter: nothing)",
  "ui.alone.test": "What would the condition say now?",
  "ui.alone.asking": "Asking the condition…",
  "ui.alone.said.go": "It would start now{reason}",
  "ui.alone.said.wait": "It would wait until {at}{reason}",
  "ui.alone.said.stop": "It would stop{reason}",
  "ui.alone.said.error": "No proper answer{reason}",
  "ui.hooks.title": "Hooks — a number turns one on or off:",
  "ui.hooks.on": "{name}: on",
  "ui.hooks.off": "{name}: off",
  "ui.hooks.none": "No hooks here yet. A hook is your own program told of what is saved (e.g. a message to your phone) — how: {readme}",
  "ui.archives.title": "Downloaders of the archives here:",
  "ui.archives.empty": "No downloaders here yet — the agent builds one when the research needs an archive.",
  "ui.archives.login.saved": "your login saved {date}",
  "ui.archives.login.none": "can use your account — no login saved",
  "ui.archives.consent": "Downloaders ask you before they run: {state}",
  "ui.archives.consent.about": "Off (usual): downloaders run by themselves — slowly, and only to their archive. On: each needs your yes first, here in the terminal, and so does each archive it reaches.",
  "ui.archives.consent.on": "Turn it on?",
  "ui.archives.consent.off": "Turn it off?",
  "ui.hooks.nothing": "none",
  "ui.menu.noagent": "No AI agent on this computer yet — the research is its work. Item 1 installs one.",
  "ui.menu.getagent": "Install or choose the AI agent",
  "ui.menu.update.where": "A new version of strom is out: {version} — update it in the settings (item {key}).",
  "ui.more.noagent": "The agent takes it up once it is on this computer (item 1 of the menu).",
  "ui.menu.noagent.chosen": "The AI agent this research uses is not on this computer — item 1 chooses another.",
  "ui.waiting.title": "The agent needs you for {n} thing(s):",
  "ui.waiting.do": "What to do: {what}",
  "ui.waiting.ask": "the agent will tell you in a conversation",
  "ui.waiting.images": "Save by hand: images {images} of {book}",
  "ui.waiting.more": "…and {n} more — the agent goes through them with you in a conversation.",
  "ui.waiting.pick": "Have you got it? Choose the number and write what you found:",
  "ui.waiting.answer": "Answer {k}: {what}",
  "ui.waiting.folder": "Open the folder for the images of {k}",
  "ui.waiting.opened": "The folder: {dir} — once the images are there, the next work of the agent takes them in by itself.",
  "ui.waiting.write": "Your answer — a link, a book's number, what you found out (Enter or 0 goes back)",
  "ui.waiting.back": "✓ The task goes back to the agent with your answer.",
  "ui.waiting.chat": "Go on with the agent now?",
  "ui.waiting.say": "I answered what you asked of me: {what} — let us go on with it.",
  "ui.intake.empty": "There is nothing in it to take in.",
  "ui.intake.ours": "{path} is strom's own folder (the research itself), not material of the family.",
  "ui.research.exists": "This research is there already: “{name}” — the agent goes on with it.",
  "ui.alone.gate.bad": "Please a number of points from 0 to 100 (e.g. 10).",
  "ui.waiting.long": "That is long for an answer here (at most {n} characters) — a link or a sentence; the rest tell the agent in a conversation.",
  "ui.settings.remote.chats": "conversations yes, working alone no",
  "ui.settings.remote.own": "Conversations with the agent you can watch from your phone already — Claude Code does it itself (its own setting). The agent working alone (item 2 of the menu) only once this is on too.",
  "ui.settings.remote.both": "conversations and working alone",
  "ui.settings.remote.onalone": "Turn it on for working alone too?",
  "ui.archives.login.nobody": "None of them needs a login: the archives are open. A login shows here only for a downloader of a portal with an account (perhaps a paid one).",
  "ui.archives.login.how": "Your login is typed in here and kept on this computer only; strom puts it into the downloader's requests — neither the downloader nor the agent sees it.",
  "ui.archives.login.save": "Save your login to {title}",
  "ui.archives.login.change": "Change your login to {title}",
  "ui.home.what": "The research is in {from} (family trees: {trees}), with the shared folder — downloaders, hooks, the inbox, big images. It moves to {to} as a whole.",
  "ui.home.sure": "Move it there?",
  "ui.home.moved": "✓ The research is in {to} now.",
  "ui.home.copied": "✓ The research is copied to {to} (another disk) and works from there. The old folder {from} is left as it was — delete it once you have seen all is well.",
  "ui.home.stays": "The research stays in {from}.",
  "ui.home.inside": "{to} is inside the research's folder {from} (or the other way round) — pick a folder beside it.",
  "ui.home.notEmpty": "{to} holds something already — the research moves only into an empty or new folder.",
  "ui.home.busy": "Somebody is at work in {trees} right now (an agent, a run, or the Strom app following it live) — the research can move once that has finished.",
  "ui.home.failed": "It could not be moved ({reason}) — nothing changed.",
  "ui.app.notinstalled": "The Strom app is not installed on this computer yet. Install it now as an app from the browser (free; strom shows where to click)?",
  "ui.browser.agent": "{names}: through the browser — that only Claude Code can (the Claude in Chrome extension); this research is done by {agent}. Save those images by hand, or let Claude Code do the research (strom agents use claude).",
  "ui.browser.noext": "{names}: through the browser — Chrome needs the Claude in Chrome extension, signed in to the account Claude Code uses; it is not in a browser here: {url}",
  "ui.doc.browser": "browser (Claude in Chrome)",
  "ui.doc.browser.ok": "the extension in {browsers} — Chrome must run while the agent works",
  "ui.doc.browser.noext": "the extension is not installed (needed by {names})",
  "ui.doc.browser.agent": "{names} go through the browser — only Claude Code can (now: {agent})",
  "ui.archives.via.direct": "images directly, paced by strom",
  "ui.archives.via.browser": "images through your browser",
  "ui.archives.via.manual": "images saved by hand (the archive allows no automation)",
  "ui.archives.browser.ok": "Through the browser: the Claude in Chrome extension is in {browsers}; Chrome must run while the agent works, signed in to the account Claude Code uses.",
  "ui.archives.to.browser": "{title}: fetch through your browser instead",
  "ui.archives.to.direct": "{title}: fetch directly instead",
  "ui.archives.browser.about": "Through your browser the agent fetches the images in your own Chrome (where your login to the archive is), with the Claude in Chrome extension — only Claude Code can. strom still plans and paces every request.",
  "ui.archives.direct.about": "Directly, strom fetches the images itself, paced, without a browser — any agent can.",
  "ui.archives.switch": "Switch it?",
  "ui.archives.now.browser": "✓ {title}: through your browser from now on.",
  "ui.archives.now.direct": "✓ {title}: directly from now on.",
  "ui.setup.home.again": "Where to keep the research (0 keeps it where it is)",
  "ui.home.env": "The research's folder {from} is set from outside (STROM_HOME) — it stays; change it there.",
  "ui.menu.failed": "That did not work: {reason}",
  "ui.review.next.human": "The agent takes them up in a conversation or when it works alone.",
  "ui.review.wake.human": "    to go on with it, tell the agent in a conversation",
  "ui.waiting.gone": "This one no longer waits for you — the agent has taken it up meanwhile.",
} as const;

export type UIKey = keyof typeof UI;

/** A text for the person, in their language. */
export function ui(lang: string, key: UIKey, values: Record<string, string | number> = {}): string {
  return localized(lang, key, UI[key], values);
}
